[k8s_masters]
k8s-master1 ansible_host=192.168.0.132 ansible_user=ubuntu
k8s-master2 ansible_host=192.168.0.133 ansible_user=ubuntu
k8s-master3 ansible_host=192.168.0.134 ansible_user=ubuntu

[k8s_workers]
k8s-worker1 ansible_host=192.168.0.135 ansible_user=ubuntu
k8s-worker2 ansible_host=192.168.0.136 ansible_user=ubuntu
k8s-worker3 ansible_host=192.168.0.137 ansible_user=ubuntu

[k8s_all:children]
k8s_masters
k8s_workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
