[k8s_masters]
k8s-master1 ansible_host=192.168.0.126 ansible_user=ubuntu
k8s-master2 ansible_host=192.168.0.127 ansible_user=ubuntu
k8s-master3 ansible_host=192.168.0.128 ansible_user=ubuntu

[k8s_workers]
k8s-worker1 ansible_host=192.168.0.129 ansible_user=ubuntu
k8s-worker2 ansible_host=192.168.0.130 ansible_user=ubuntu
k8s-worker3 ansible_host=192.168.0.131 ansible_user=ubuntu

[k8s_all:children]
k8s_masters
k8s_workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
